services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rajat
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - rajatKaNetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flask-app:
    # If the image is not available and 'build' option is not there
    # docker pull the image from Docker Hub
    # image: rajatcantcode/2-tier-flask-app-img:latest

    # If you want to build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    image: 2-tier-flask-app-img
    container_name: 2-tier-flask-app
    ports:
      - "5001:5001"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: rajat
    depends_on:
      - mysql
    networks:
      - rajatKaNetwork
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:

networks:
  rajatKaNetwork:
