apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
spec:
  containers:
    - name: two-tier-app-pod
      image: rajatcantcode/2-tier-flask-app-img:latest
      env:
        - name: MYSQL_HOST
          value: "00.00.00.000" # TODO : Change mysql's service clusture IP with yours
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_DB
          value: "mydb"
      ports:
        - containerPort: 5001
      imagePullPolicy: Always
